#!/usr/bin/env bash
# tools/dbc/overhead.sh
# SC-008 checked-build overhead measurement (T018 / Principle VII).
#
# Compiles tools/dbc/overhead.cpp at -O2, runs the A/B hot loop, and
# regenerates docs/pages/dbc-overhead.md with the min/max/n50/n99
# distribution. This is a documented measurement, not a CI gate:
# nothing here is registered with CTest.
#
# Usage: bash tools/dbc/overhead.sh [include-dir]
# Env:   OVERHEAD_N (default 100000000), OVERHEAD_TRIALS (default 51)
#
# Exit 0 if the measurement is valid (uncontracted baseline > 0 and
# contracted >= baseline, with each uncontracted trial >= 1ms).
# Exit 1 on invalid measurement (tiny N is the invalidity probe).

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd -P)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd -P)
SRC="$SCRIPT_DIR/overhead.cpp"
OUT="$REPO_ROOT/docs/pages/dbc-overhead.md"
INCLUDE=${1:-"$REPO_ROOT/include"}
N=${OVERHEAD_N:-100000000}
TRIALS=${OVERHEAD_TRIALS:-51}

if [ ! -f "$SRC" ]; then
  echo "overhead.sh: missing $SRC" >&2
  exit 1
fi
if [ ! -d "$INCLUDE" ]; then
  echo "overhead.sh: include dir not found: $INCLUDE" >&2
  exit 1
fi
if ! command -v g++ >/dev/null 2>&1; then
  echo "overhead.sh: g++ is required" >&2
  exit 1
fi

WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT

CXX_FLAGS="-std=c++20 -O2 -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion -Wshadow -Wold-style-cast"

compile() {
  local cxx=$1
  local bin=$2
  "$cxx" $CXX_FLAGS -I "$INCLUDE" -DSG_CONTRACTS_SEMANTIC=2 "$SRC" -o "$bin"
}

run_bin() {
  local bin=$1
  local out=$2
  local runner=()
  if command -v taskset >/dev/null 2>&1; then
    runner=(taskset -c 0)
  fi
  if command -v timeout >/dev/null 2>&1; then
    timeout 120 "${runner[@]}" "$bin" "$N" "$TRIALS" >"$out"
  else
    "${runner[@]}" "$bin" "$N" "$TRIALS" >"$out"
  fi
}

kv() {
  local file=$1
  local key=$2
  sed -n "s/^${key}=//p" "$file" | tail -1
}

MEASURED_AT=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
UPTIME_TXT=$(uptime)
if [ -r /proc/loadavg ]; then
  LOADAVG_TXT=$(cat /proc/loadavg)
else
  LOADAVG_TXT="(unavailable)"
fi
HOST_TXT=$(uname -srm 2>/dev/null || uname)

GPP_VER=$(g++ --version | head -1)
GPP_BIN="$WORKDIR/overhead-g++"
GPP_OUT="$WORKDIR/g++.txt"
compile g++ "$GPP_BIN"
run_bin "$GPP_BIN" "$GPP_OUT"

CLANG_SECTION=""
if command -v clang++ >/dev/null 2>&1; then
  CLANG_VER=$(clang++ --version | head -1)
  CLANG_BIN="$WORKDIR/overhead-clang++"
  CLANG_OUT="$WORKDIR/clang++.txt"
  compile clang++ "$CLANG_BIN"
  run_bin "$CLANG_BIN" "$CLANG_OUT"
fi

section_for() {
  local title=$1
  local ver=$2
  local file=$3
  cat <<EOF
## ${title}

Toolchain: \`${ver}\`

| metric | ns/iter |
| --- | --- |
| uncontracted min | $(kv "$file" uncontracted_ns_per_iter_min) |
| uncontracted max | $(kv "$file" uncontracted_ns_per_iter_max) |
| uncontracted n50 | $(kv "$file" uncontracted_ns_per_iter_n50) |
| uncontracted n99 | $(kv "$file" uncontracted_ns_per_iter_n99) |
| contracted min | $(kv "$file" contracted_ns_per_iter_min) |
| contracted max | $(kv "$file" contracted_ns_per_iter_max) |
| contracted n50 | $(kv "$file" contracted_ns_per_iter_n50) |
| contracted n99 | $(kv "$file" contracted_ns_per_iter_n99) |
| overhead min | $(kv "$file" overhead_ns_per_iter_min) |
| overhead max | $(kv "$file" overhead_ns_per_iter_max) |
| overhead n50 | $(kv "$file" overhead_ns_per_iter_n50) |
| overhead n99 | $(kv "$file" overhead_ns_per_iter_n99) |

Totals: uncontracted $(kv "$file" uncontracted_sum_ns) ns, contracted $(kv "$file" contracted_sum_ns) ns over $(kv "$file" trials) trials of N=$(kv "$file" n). Validity: $(kv "$file" reason).

### Raw trial inputs (ns/iter, trial order)

uncontracted:

\`\`\`
$(kv "$file" raw_uncontracted_ns_per_iter)
\`\`\`

contracted:

\`\`\`
$(kv "$file" raw_contracted_ns_per_iter)
\`\`\`

overhead (contracted minus uncontracted):

\`\`\`
$(kv "$file" raw_overhead_ns_per_iter)
\`\`\`
EOF
}

GPP_SECTION=$(section_for "g++" "$GPP_VER" "$GPP_OUT")
if [ -n "${CLANG_OUT:-}" ]; then
  CLANG_SECTION=$(section_for "clang++" "$CLANG_VER" "$CLANG_OUT")
else
  CLANG_SECTION="## clang++

clang++ was not present; no second data point was collected."
fi

# Regenerated from scratch every run (stale_state: never append).
cat >"$OUT" <<EOF
# DBC checked-build overhead (SC-008)

Documented measurement of the checked-build (\`enforce\`) cost of a
satisfied \`SG_REQUIRE\` versus an identical uncontracted hot loop.
This is **not** a CI gate or per-PR assertion (constitution Principle
VII; T018). Release (\`ignore\`) zero added cost is proven by code
absence, not by timing.

Generated by \`tools/dbc/overhead.sh\` at ${MEASURED_AT}. Re-running
the script rewrites this file.

## Protocol

- Clock: \`std::chrono::steady_clock\`
- Optimization: \`-O2 -std=c++20\` (no LTO)
- Semantic: \`SG_CONTRACTS_SEMANTIC=2\` (enforce)
- Iterations per trial (N): ${N}
- Trials: ${TRIALS}
- Payload: per-iteration volatile load plus integer add, in a
  \`noinline\` function so the loop is not strength-reduced
- Contracted loop: the same payload plus a satisfied \`SG_REQUIRE\`
  whose predicate is the volatile-loaded runtime value (\`cur > 0\`)
- Pairing: two full-N warmups, then ABBA (U-C-C-U / C-U-U-C) per trial
- Overhead: contracted minus uncontracted, nanoseconds per iteration
- Distribution: min / max / n50 / n99 over the per-trial overheads
  (nearest-rank percentiles)
- Validity: uncontracted baseline > 0, each uncontracted trial at
  least 1 ms, and contracted n50 >= 90% of uncontracted n50 (a
  predicted branch is often inside clock noise; 10% is the
  credibility band, not a performance gate)
- Bound: each binary is run under \`timeout 120\`

## Load context

Host: \`${HOST_TXT}\`

uptime:

\`\`\`
${UPTIME_TXT}
\`\`\`

load average (\`/proc/loadavg\`):

\`\`\`
${LOADAVG_TXT}
\`\`\`

Measurements taken on a contended host MUST NOT be treated as a
platform baseline (Principle VII). This file records the load so a
reader can judge credibility.

${GPP_SECTION}

${CLANG_SECTION}

## Interpretation

The overhead n50 is the typical per-check cost of a satisfied
\`SG_REQUIRE\` in a checked (\`enforce\`) build. Long tails (n99 vs
n50, max vs n50) are part of the distribution; they are not discarded.
The \`ignore\` build elides semantic-gated checks to nothing (SC-002);
that zero-cost claim is a code-absence proof, not a timing claim.
EOF

echo "overhead.sh: wrote $OUT"
echo "overhead.sh: g++ valid=$(kv "$GPP_OUT" valid) n50=$(kv "$GPP_OUT" overhead_ns_per_iter_n50) ns/iter"
if [ -n "${CLANG_OUT:-}" ]; then
  echo "overhead.sh: clang++ valid=$(kv "$CLANG_OUT" valid) n50=$(kv "$CLANG_OUT" overhead_ns_per_iter_n50) ns/iter"
fi
